Prebuild custom redis image and use it for testing in CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,8 +14,10 @@ jobs:
     outputs:
       CACHE_KEY_BASE: ${{ steps.mainstep.outputs.CACHE_KEY_BASE }}
       CACHE_KEY_AGENCY: ${{ steps.mainstep.outputs.CACHE_KEY_AGENCY }}
+      CACHE_KEY_REDIS: ${{ steps.mainstep.outputs.CACHE_KEY_REDIS }}
       CACHED_DOCKER_IMG_NAME_BASE: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_BASE }}
       CACHED_DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_AGENCY }}
+      CACHED_DOCKER_IMG_NAME_REDIS: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_REDIS }}
       PUBLISH_DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.PUBLISH_DOCKER_IMG_NAME_AGENCY }}
       PUBLISH_VERSION: ${{ steps.mainstep.outputs.PUBLISH_VERSION }}
       RELEASE: ${{ steps.mainstep.outputs.RELEASE }}
@@ -101,8 +103,10 @@ jobs:
 
           echo "::set-output name=CACHE_KEY_BASE::$DOCKER_BASE_HASH"
           echo "::set-output name=CACHE_KEY_AGENCY::$(echo basehash-$CACHE_KEY_BASE-agencyhash-$CODE_AGENCY_HASH-clienthash-$CODE_CLIENT_HASH-easyindysdkhash-$CODE_EASYSDK_HASH)"
+          echo "::set-output name=CACHE_KEY_REDIS::${{ hashFiles('ci/redis') }}"
           echo "::set-output name=CACHED_DOCKER_IMG_NAME_BASE::vcxagency-base:cached"
           echo "::set-output name=CACHED_DOCKER_IMG_NAME_AGENCY::vcxagency-node:cached"
+          echo "::set-output name=CACHED_DOCKER_IMG_NAME_REDIS::redis:cached"
 
           echo "::set-output name=PUBLISH_DOCKER_IMG_NAME_AGENCY::vcxagency-node:$PUBLISH_VERSION"
 
@@ -134,6 +138,31 @@ jobs:
           vcxagency-base/build.sh "$CACHED_DOCKER_IMG_NAME_BASE"
           mkdir -p /tmp/imgcache
           docker save "$CACHED_DOCKER_IMG_NAME_BASE" > /tmp/imgcache/img_base.rar
+          docker image ls
+
+  build-vcxagency-redis:
+    needs:
+      - workflow-setup
+    runs-on: ubuntu-latest
+    env:
+      DOCKER_BUILDKIT: 1
+      CACHE_KEY_REDIS: ${{needs.workflow-setup.outputs.CACHE_KEY_REDIS}}
+      CACHED_DOCKER_IMG_NAME_REDIS: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_REDIS}}
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v2
+      - name: Try load from cache.
+        id: cache-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_REDIS }}
+      - name: If NOT found in cache, Build and cache image.
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        run: |
+          cd ci/redis;
+          docker build -t "$CACHED_DOCKER_IMG_NAME_REDIS"
+          docker save "$CACHED_DOCKER_IMG_NAME_REDIS" > /tmp/imgcache/image.rar
           docker image ls
 
   build-image-vcxagency:
@@ -203,6 +232,8 @@ jobs:
     env:
       CACHE_KEY_AGENCY: ${{needs.workflow-setup.outputs.CACHE_KEY_AGENCY}}
       CACHED_DOCKER_IMG_NAME_AGENCY: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_AGENCY}}
+      CACHE_KEY_REDIS: ${{needs.workflow-setup.outputs.CACHE_KEY_REDIS}}
+      CACHED_DOCKER_IMG_NAME_REDIS: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_REDIS}}
     steps:
       - name: Git checkout
         uses: actions/checkout@v2
@@ -220,8 +251,25 @@ jobs:
       - name: Load agency image from cache
         run: docker load < /tmp/imgcache/img_agency.rar
 
-      - name: Verify image was loaded
+      - name: Verify agency image was loaded
         run: docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_AGENCY" || { echo "Image $CACHED_DOCKER_IMG_NAME_AGENCY was not found!"; docker image ls; exit 1; }
+
+      - name: Load redis image cache
+        id: load-cached-image-node
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_REDIS }}
+
+      - name: If no cached image found -> ERROR
+        if: steps.load-cached-image-node.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_REDIS"; exit -1
+
+      - name: Load Redis image from cache
+        run: docker load < /tmp/imgcache/image.rar
+
+      - name: Verify Redis image was loaded
+        run: docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_REDIS" || { echo "Image $CACHED_DOCKER_IMG_NAME_REDIS was not found!"; docker image ls; exit 1; }
 
       - name: Run tests
         run: |
