Use vdr-tools+mysql instead of libindy+pgsql

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,7 @@ jobs:
       CACHED_DOCKER_IMG_NAME_BASE: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_BASE }}
       CACHED_DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_AGENCY }}
       CACHED_DOCKER_IMG_NAME_REDIS: ${{ steps.mainstep.outputs.CACHED_DOCKER_IMG_NAME_REDIS }}
+      PUBLISH_DOCKER_IMG_NAME_BASE: ${{ steps.mainstep.outputs.PUBLISH_DOCKER_IMG_NAME_BASE }}
       PUBLISH_DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.PUBLISH_DOCKER_IMG_NAME_AGENCY }}
       PUBLISH_DOCKER_IMG_NAME_REDIS: ${{ steps.mainstep.outputs.PUBLISH_DOCKER_IMG_NAME_REDIS }}
       PUBLISH_VERSION: ${{ steps.mainstep.outputs.PUBLISH_VERSION }}
@@ -98,20 +99,23 @@ jobs:
           fi;
 
           # change REBUILD_SEED if you want to manually enforce rebuilding all images
-          REBUILD_SEED="1"
+          REBUILD_SEED_REDIS="1"
+          REBUILD_SEED_BASE="2"
+          REBUILD_SEED_AGENCY="1"
 
           export CODE_AGENCY_HASH=${{ hashFiles('vcxagency-node') }}
           export CODE_CLIENT_HASH=${{ hashFiles('vcxagency-client') }}
           export CODE_EASYSDK_HASH=${{ hashFiles('easy-indysdk') }}
 
-          echo "::set-output name=CACHE_KEY_REDIS::$REBUILD_SEED-${{ hashFiles('ci/redis') }}"
-          echo "::set-output name=CACHE_KEY_BASE::$REBUILD_SEED-${{ hashFiles('vcxagency-base') }}"
-          echo "::set-output name=CACHE_KEY_AGENCY::$REBUILD_SEED-$(echo basehash-$CACHE_KEY_BASE-agencyhash-$CODE_AGENCY_HASH-clienthash-$CODE_CLIENT_HASH-easyindysdkhash-$CODE_EASYSDK_HASH)"
+          echo "::set-output name=CACHE_KEY_REDIS::$REBUILD_SEED_REDIS-${{ hashFiles('ci/redis') }}"
+          echo "::set-output name=CACHE_KEY_BASE::$REBUILD_SEED_BASE-${{ hashFiles('vcxagency-base') }}"
+          echo "::set-output name=CACHE_KEY_AGENCY::$REBUILD_SEED_AGENCY-$(echo basehash-$CACHE_KEY_BASE-agencyhash-$CODE_AGENCY_HASH-clienthash-$CODE_CLIENT_HASH-easyindysdkhash-$CODE_EASYSDK_HASH)"
 
           echo "::set-output name=CACHED_DOCKER_IMG_NAME_BASE::vcxagency-base:cached"
           echo "::set-output name=CACHED_DOCKER_IMG_NAME_AGENCY::vcxagency-node:cached"
           echo "::set-output name=CACHED_DOCKER_IMG_NAME_REDIS::redis:cached"
 
+          echo "::set-output name=PUBLISH_DOCKER_IMG_NAME_BASE::vcxagency-base:$PUBLISH_VERSION"
           echo "::set-output name=PUBLISH_DOCKER_IMG_NAME_AGENCY::vcxagency-node:$PUBLISH_VERSION"
           echo "::set-output name=PUBLISH_DOCKER_IMG_NAME_REDIS::vcxagency-redis:$PUBLISH_VERSION"
 
@@ -125,7 +129,7 @@ jobs:
       - workflow-setup
     runs-on: ubuntu-latest
     env:
-      DOCKER_BUILDKIT: 1
+#      DOCKER_BUILDKIT: 1
       CACHE_KEY_BASE: ${{needs.workflow-setup.outputs.CACHE_KEY_BASE}}
       CACHED_DOCKER_IMG_NAME_BASE: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_BASE}}
     steps:
@@ -140,9 +144,54 @@ jobs:
       - name: If NOT found in cache, build and cache image.
         if: steps.cache-image.outputs.cache-hit != 'true'
         run: |
+          echo "This is running"
           vcxagency-base/build.sh "$CACHED_DOCKER_IMG_NAME_BASE"
           mkdir -p /tmp/imgcache-base
           docker save "$CACHED_DOCKER_IMG_NAME_BASE" > /tmp/imgcache-base/image.rar
+
+  docker-publish-vcxagency-base:
+    needs:
+      - workflow-setup
+      - build-vcxagency-base
+    if: ${{ needs.workflow-setup.outputs.RELEASE == 'false' && needs.workflow-setup.outputs.PRERELEASE == 'false' }}
+    runs-on: ubuntu-latest
+    env:
+      CACHE_KEY_BASE: ${{needs.workflow-setup.outputs.CACHE_KEY_BASE}}
+      CACHED_DOCKER_IMG_NAME_BASE: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_BASE}}
+      PUBLISH_DOCKER_IMG_NAME_BASE: ${{needs.workflow-setup.outputs.PUBLISH_DOCKER_IMG_NAME_BASE}}
+    steps:
+      - name: Load base image
+        id: load-cached-image-node
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache-base
+          key: ${{ env.CACHE_KEY_BASE }}
+
+      - name: If no cached image found -> ERROR
+        if: steps.load-cached-image-node.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_BASE"; exit -1
+
+      - name: Load base image
+        run: docker load < /tmp/imgcache-base/image.rar
+
+      - name: Verify images were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_BASE" || { echo "Image $CACHED_DOCKER_IMG_NAME_BASE was not found!"; docker image ls; exit 1; }
+
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish images
+        run: |
+          GITHUB_REPOSITORY_LOWERCASE=`echo $GITHUB_REPOSITORY | awk '{print tolower($0)}'`
+          REMOTE_DOCKER_IMG_NAME_BASE="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$PUBLISH_DOCKER_IMG_NAME_BASE"
+          docker tag "$CACHED_DOCKER_IMG_NAME_BASE" "$REMOTE_DOCKER_IMG_NAME_BASE"
+          docker image ls
+          docker push "$REMOTE_DOCKER_IMG_NAME_BASE" || true
 
   build-vcxagency-redis:
     needs:
@@ -227,6 +276,50 @@ jobs:
         run: |
           docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_AGENCY" || { echo "Image $CACHED_DOCKER_IMG_NAME_AGENCY was not found!"; docker image ls; exit 1; }
 
+  docker-publish-image-vcxagency:
+    needs:
+      - workflow-setup
+      - build-image-vcxagency
+    if: ${{ needs.workflow-setup.outputs.RELEASE == 'false' && needs.workflow-setup.outputs.PRERELEASE == 'false' }}
+    runs-on: ubuntu-latest
+    env:
+      CACHE_KEY_AGENCY: ${{needs.workflow-setup.outputs.CACHE_KEY_AGENCY}}
+      CACHED_DOCKER_IMG_NAME_AGENCY: ${{needs.workflow-setup.outputs.CACHED_DOCKER_IMG_NAME_AGENCY}}
+      PUBLISH_DOCKER_IMG_NAME_AGENCY: ${{needs.workflow-setup.outputs.PUBLISH_DOCKER_IMG_NAME_AGENCY}}
+    steps:
+      - name: Load cached image
+        id: load-cached-image-node
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache-agency
+          key: ${{ env.CACHE_KEY_AGENCY }}
+
+      - name: If no cached image found -> ERROR
+        if: steps.load-cached-image-node.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_AGENCY"; exit -1
+
+      - name: Load image
+        run: docker load < /tmp/imgcache-agency/image.rar
+
+      - name: Verify images were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_AGENCY" || { echo "Image $CACHED_DOCKER_IMG_NAME_AGENCY was not found!"; docker image ls; exit 1; }
+
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish images
+        run: |
+          GITHUB_REPOSITORY_LOWERCASE=`echo $GITHUB_REPOSITORY | awk '{print tolower($0)}'`
+          REMOTE_DOCKER_IMG_NAME="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$PUBLISH_DOCKER_IMG_NAME_AGENCY"
+          docker tag "$CACHED_DOCKER_IMG_NAME_AGENCY" "$REMOTE_DOCKER_IMG_NAME"
+          docker image ls
+          docker push "$REMOTE_DOCKER_IMG_NAME" || true
+
   test-unit-vcxagency:
     runs-on: ubuntu-latest
     needs:
@@ -277,8 +370,13 @@ jobs:
       - name: Run tests
         run: |
           set -x
-          docker-compose -f ci/docker-compose.yml -f ci/docker-compose.pg.yml -f ci/docker-compose.redis.yml up -d
+          docker-compose -f ci/docker-compose.yml \
+                         -f ci/docker-compose.pg.yml \
+                         -f ci/docker-compose.mysql.yml \
+                         -f ci/docker-compose.redis.yml \
+                         up -d
           sleep 5
+          docker ps -a
           docker run --rm --name vcxagencynode \
                         --network host \
                          "$CACHED_DOCKER_IMG_NAME_AGENCY" \
@@ -318,7 +416,7 @@ jobs:
                          "$CACHED_DOCKER_IMG_NAME_AGENCY" \
                          bash -c "cd /home/node/easy-indysdk && yarn install && yarn run test:unit"
 
-  test-integration-indysdk-pgsql:
+  test-integration-indysdk-mysql:
     runs-on: ubuntu-latest
     needs:
       - build-image-vcxagency
@@ -347,15 +445,14 @@ jobs:
       - name: Git checkout
         uses: actions/checkout@v2
 
-      - name: Run easy-indysdk pgsql integration test
+      - name: Run easy-indysdk mysql integration test
         run: |
           set -x
-          docker run --rm -d \
-                     --name postgres \
-                     --network host \
-                     -e POSTGRES_USER=postgres \
-                     -e POSTGRES_PASSWORD=mysecretpassword \
-                     postgres:12.1
+          docker run -d -p 3306:3306 \
+                     --name mysql \
+                     -v mysqldata:/var/lib/mysql \
+                     -e MYSQL_ROOT_PASSWORD=mysecretpassword \
+                      mysql:5.7.35
           sleep 5
           docker run --rm \
                      --name vcxagencynode \
@@ -451,11 +548,13 @@ jobs:
           export AGENCY_IMAGE="$CACHED_DOCKER_IMG_NAME_AGENCY"
           docker-compose -f ./ci/docker-compose.yml \
                          -f ./ci/docker-compose.agency-ca.yml \
+                         -f ./ci/docker-compose.mysql.yml \
                          -f ./ci/docker-compose.pg.yml \
                          -f ./ci/docker-compose.redis.yml up -d
-          sleep 5
+          sleep 10
           docker-compose -f ./ci/docker-compose.yml \
                          -f ./ci/docker-compose.agency-ca.yml \
+                         -f ./ci/docker-compose.mysql.yml \
                          -f ./ci/docker-compose.pg.yml \
                          -f ./ci/docker-compose.redis.yml logs
 
@@ -474,6 +573,7 @@ jobs:
           docker-compose -f ./ci/docker-compose.yml \
                          -f ./ci/docker-compose.agency-ca.yml \
                          -f ./ci/docker-compose.pg.yml \
+                         -f ./ci/docker-compose.mysql.yml \
                          -f ./ci/docker-compose.redis.yml \
                          down
 
@@ -483,11 +583,15 @@ jobs:
           export AGENCY_IMAGE="$CACHED_DOCKER_IMG_NAME_AGENCY"
           docker-compose -f ./ci/docker-compose.yml \
                          -f ./ci/docker-compose.agency-ea.yml \
-                         -f ./ci/docker-compose.pg.yml up -d
-          sleep 5
+                         -f ./ci/docker-compose.mysql.yml \
+                         -f ./ci/docker-compose.pg.yml \
+                          up -d
+          sleep 10
           docker-compose -f ./ci/docker-compose.yml \
                          -f ./ci/docker-compose.agency-ea.yml \
-                         -f ./ci/docker-compose.pg.yml logs
+                         -f ./ci/docker-compose.pg.yml \
+                         -f ./ci/docker-compose.mysql.yml \
+                         logs
 
       - name: E2E Test enterprise agency
         run: |
@@ -533,7 +637,7 @@ jobs:
         run: |
           cd easy-indysdk && standard
 
-  publish-images:
+  docker-publish-images-all:
     needs:
       - workflow-setup
       - build-vcxagency-base
@@ -545,6 +649,7 @@ jobs:
       - lint-vcxagency-node
       - lint-vcxagency-client
       - lint-easy-indysdk
+    if: ${{ needs.workflow-setup.outputs.RELEASE == 'true' || needs.workflow-setup.outputs.PRERELEASE == 'true' }}
     runs-on: ubuntu-latest
     env:
       CACHE_KEY_AGENCY: ${{needs.workflow-setup.outputs.CACHE_KEY_AGENCY}}
@@ -571,7 +676,6 @@ jobs:
       - name: Verify images were loaded
         run: |
           docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$CACHED_DOCKER_IMG_NAME_AGENCY" || { echo "Image $CACHED_DOCKER_IMG_NAME_AGENCY was not found!"; docker image ls; exit 1; }
-
 
       - name: Load Redis image cache
         id: load-cached-image-redis
